#pragma once

#define NUM_LEDS 30
#define NUM_LEDS_DOOR_FR 7

#define DASH_BOTTOM_PIN 2
#define DASH_BOTTOM_NUM_LEDS 128

#define DASH_BOTTOM_LED_DAY_BRIGHTNESS 255
#define DASH_BOTTOM_LED_NIGHT_BRIGHTNESS 30
#define DASH_BOTTOM_LED_COLOR CRGB::Blue

#define MOBILE_CHRGR_LED_DAY_BRIGHTNESS 255
#define MOBILE_CHRGR_LED_NIGHT_BRIGHTNESS 20
#define MOBILE_CHRGR_LED_COLOR CRGB::White

#define DOOR_POCKET_DAY_BRIGHTNESS 255
#define DOOR_POCKET_NIGHT_BRIGHTNESS 20
#define DOOR_POCKET_COLOR CRGB::White
#define DOOR_POCKET_V2_COLOR CRGB::White

#define DOOR_SPEAKER_DAY_BRIGHTNESS 255
#define DOOR_SPEAKER_NIGHT_BRIGHTNESS 255
#define DOOR_SPEAKER_COLOR CRGB::Blue

#define DATA_PIN_DOOR_FR_SPEAKER 4
#define NUM_LEDS_DOOR_FR_SPEAKER 10

#define DATA_PIN_DOOR_FR_POCKET 7
#define NUM_LEDS_DOOR_FR_POCKET 7

#define DATA_PIN_DOOR_FL_SPEAKER 5
#define NUM_LEDS_DOOR_FL_SPEAKER 10

#define DATA_PIN_DOOR_FL_POCKET 13
#define NUM_LEDS_DOOR_FL_POCKET 53

CRGB leds[NUM_LEDS];
CRGB charging_station_leds[NUM_LEDS];
CRGB door_fr_leds[NUM_LEDS_DOOR_FR];
CRGB door_fr_leds_speaker[NUM_LEDS_DOOR_FR_SPEAKER];
CRGB door_fr_leds_pocket[NUM_LEDS_DOOR_FR_POCKET];
CRGB dash_bottom_leds[DASH_BOTTOM_NUM_LEDS];
CRGB door_fl_leds_speaker[NUM_LEDS_DOOR_FL_SPEAKER];
CRGB door_fl_leds_pocket[NUM_LEDS_DOOR_FL_POCKET];