#pragma once

#define NUM_LEDS 30
#define NUM_LEDS_DOOR_FR 7

#define DASH_BOTTOM_PIN 2
#define DASH_BOTTOM_NUM_LEDS 128

#define DASH_BOTTOM_LED_DAY_BRIGHTNESS 255
#define DASH_BOTTOM_LED_NIGHT_BRIGHTNESS 30

#define MOBILE_CHRGR_LED_DAY_BRIGHTNESS 255
#define MOBILE_CHRGR_LED_NIGHT_BRIGHTNESS 20

#define DOOR_POCKET_DAY_BRIGHTNESS 255
#define DOOR_POCKET_NIGHT_BRIGHTNESS 20

#define DOOR_SPEAKER_DAY_BRIGHTNESS 255
#define DOOR_SPEAKER_NIGHT_BRIGHTNESS 255

#define DATA_PIN_DOOR_FR_SPEAKER 4
#define NUM_LEDS_DOOR_FR_SPEAKER 10

#define DATA_PIN_DOOR_FR_POCKET 7
#define NUM_LEDS_DOOR_FR_POCKET 7

#define DATA_PIN_DOOR_FL_SPEAKER 5
#define NUM_LEDS_DOOR_FL_SPEAKER 10

#define DATA_PIN_DOOR_FL_POCKET 13
#define NUM_LEDS_DOOR_FL_POCKET 53